---
title: "Geocoding"
subtitle: "cleaning"
author: "Xiaoyu Liu"
date: "Aug 2020"
output: 
    html_notebook: default
    html_document: default
---
```{r, echo = FALSE, message=FALSE, warning=FALSE}

options(scipen = 9999)

install.packages("tidyverse", dependencies = TRUE)
library("tidyverse")
install.packages("rvest", dependencies = TRUE)
library("rvest")
install.packages("stringi", dependencies = TRUE)
library("stringi")
install.packages("lubridate", dependencies = TRUE)
library("lubridate")
install.packages("jsonlite", dependencies = TRUE)
library("jsonlite")

```

```{r}
# INPUT LOCATION VARIABLES
# [RECORD_ID], [Address], [City] , [State] , [Zipcode]

geocode<-function(record_id, address,city,state,zipcode){
   # NOMINATIM SEARCH API URL
  src_url <- "https://nominatim.openstreetmap.org/search?q="
  
  city <- str_replace_all(string = city, pattern = "\\s|,", replacement = "+")
  
  # CREATE A FULL ADDRESS
  addr <- paste(address, city, state, zipcode, sep = "%2C")
  # CREATE A SEARCH URL BASED ON NOMINATIM API TO RETURN GEOJSON
  requests <- paste0(src_url, addr, "&format=geojson")
  
  # ITERATE OVER THE URLS AND MAKE REQUEST TO THE SEARCH API
  for (i in 1:length(requests)) {
    
    # MAKE HTML REQUEST TO API AND TRANSFORME HTML RESPONSE TO JSON
    response <- read_html(requests[i]) %>%
      html_node("p") %>%
      html_text() %>%
      fromJSON()
    
    # FROM THE RESPONSE EXTRACT LATITUDE AND LONGITUDE COORDINATES
    lon <- response$features$geometry$coordinates[[1]][1]
    lat <- response$features$geometry$coordinates[[1]][2]
    
    # CREATE A COORDINATES DATAFRAME
    if(i == 1) {
      loc <- tibble(record_id = record_id[i], 
                    address = str_replace_all(addr[i], "%2C", ","),
                    latitude = lat, longitude = lon)
    }else{
      df <- tibble(record_id = record_id[i], 
                   address = str_replace_all(addr[i], "%2C", ","),
                   latitude = lat, longitude = lon)
      loc <- bind_rows(loc, df)
    }
  }
  return(loc)
}


```

```{r}
### Lets change the name of some columns and remote other that are irrelevant for this use case.
##load bldg_df dataset

colremove = c("First Construction Document Date",
              "Structural Notification",
              "Number of Existing Stories",
              "Number of Proposed Stories",
              "Voluntary Soft-Story Retrofit",
              "Fire Only Permit","Existing Units",
              "Proposed Units","Plansets",
              "TIDF Compliance","Existing Construction Type",
              "Proposed Construction Type","Site Permit",
              "Supervisor District","Current Police Districts",
              "Current Supervisor Districts",
              "Current Status Date", "Permit Creation Date",
              "Analysis Neighborhoods","Lot","Location",
              "SF Find Neighborhoods","Unit","Block", "Permit Type",
              "Unit Suffix","Street Number Suffix",
              "Existing Construction Type Description")

data <- data[colnames(data)[1:47]] %>% select(-all_of(colremove))

data <- rename(data, "Neighborhoods Boundaries" = "Neighborhoods - Analysis Boundaries")

data <- rename(data, "Permit Type" = "Permit Type Definition")

```

```{r}
bldg_df$record_id <- as.character(bldg_df$record_id)

bldg_df$proposed_construction_type_description <-
  bldg_df$proposed_construction_type_description %>% 
  str_remove_all(pattern = "\\(|\\)") %>% 
  str_replace_all(" ", "_") %>% 
  as_factor()

bldg_df$street_name <- str_remove(string = bldg_df$street_name, pattern = "^0+")

bldg_df$street_name <- str_replace_all(string = bldg_df$street_name,
                                       pattern = "Bay Shore",
                                       replacement = "Bayshore")

bldg_df$street_suffix <- str_replace_all(string = bldg_df$street_suffix,
                                       pattern = "Bl",
                                       replacement = "Blvd")

bldg_df$street_suffix <- str_replace_all(string = bldg_df$street_suffix,
                                       pattern = "Tr",
                                       replacement = "Ter")

bldg_df$changed_use <- bldg_df$existing_use != bldg_df$proposed_use
bldg_df$estimated_revised_diff <- bldg_df$revised_cost - bldg_df$estimated_cost
```

```{r}
bldg_df$issued_date <- bldg_df$issued_date %>% mdy() %>% as_date()
bldg_df$issued_year <- bldg_df$issued_date %>% year()
bldg_df$issued_month <- bldg_df$issued_date %>% month(label = TRUE)
bldg_df$completed_date <- bldg_df$completed_date %>% mdy() %>% as_date()
bldg_df$completed_year <- bldg_df$completed_date %>% year()
bldg_df$completed_month <- bldg_df$completed_date %>% month(label = TRUE)

bldg_df$issued_completed_days <- bldg_df$completed_date - bldg_df$issued_date 
bldg_df$issued_completed_years <- bldg_df$completed_year - bldg_df$issued_year 

bldg_df$filed_date <- bldg_df$filed_date %>% mdy() %>% as_date()
bldg_df$filed_issued_days <- bldg_df$issued_date - bldg_df$filed_date

bldg_df$permit_expiration_date <- bldg_df$permit_expiration_date %>% mdy() %>% as_date()
bldg_df$issued_expiration_days <- bldg_df$permit_expiration_date - bldg_df$issued_date
```

```{r}
bldg_df <- bldg_df %>% arrange(desc(estimated_cost))
bldg_df <- bldg_df[bldg_df$changed_use == TRUE,]
bldg_df <- bldg_df %>% filter(revised_cost > 500000)

bldg_df$zipcode <- as_factor(bldg_df$zipcode)
bldg_df$permit_type <- as_factor(bldg_df$permit_type)
bldg_df$neighborhoods_boundaries <- as_factor(bldg_df$neighborhoods_boundaries)
bldg_df$proposed_use <- as_factor(bldg_df$proposed_use)

head(bldg_df)
```

```{r}
# ADDRESS VARIABLE MUST MATH NOMINATIM API
address <- paste0(bldg_df$street_number," ",
                  bldg_df$street_name," ",
                  bldg_df$street_suffix)

# DATA CLEANING SPECIAL CASES (e.g. 3333-3339 N CLARK)
query <- stri_replace(str = address, 
                      replacement = "", 
                      regex = "(-[0-9]+\\s)")

# REPLACE SPACES (\\s) OR COMMAS (,) WITH + SIGN
query <- str_replace_all(string = query, 
                         pattern = "\\s|,", 
                         replacement = "+")

head(query)
```

```{r}
df <- geocode(record_id = bldg_df$record_id,
              address = query,
              city = bldg_df$city, 
              state = bldg_df$state,
              zipcode = bldg_df$zipcode)
```